version: "2"
run:
  go: "1.25"
  timeout: 20s
  tests: true
linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - misspell
    - nakedret
    - prealloc
    - revive
    - unconvert
    - unparam
  disable:
    - depguard
    - dupl
    - goconst
    - gocyclo
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    govet:
      disable:
        - shadow
    misspell:
      locale: UK
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: true
  exclusions:
    paths:
      - generated
      - '.*\.pb\.go'
    rules:
      - path: '(.+)\.pb\.go'
        text: '.*'
      - path: generated
        text: '.*'
      - path: '.*'
        text: 'Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv|.*Disconnect). is not checked'
      - path: '.*'
        text: 'exported var \w+ should have comment or be unexported'
      - path: '.*'
        text: 'func name will be used as test\.Test.* by other packages'
      - path: '.*'
        text: 'Use of unsafe calls should be audited'
      - path: '.*'
        text: 'Subprocess launch(ed with variable|ing should be audited)'
      - path: '.*'
        text: G104
      - path: '.*'
        text: G107
      - path: '.*'
        text: '(Expect directory permissions to be 0750 or less|Expect file permissions to be 0600 or less)'
      - path: '.*'
        text: 'Potential file inclusion via variable'
      - path: '.*'
        text: '(possible misuse of unsafe.Pointer|should have signature)'
      - path: '.*'
        text: 'ineffective break statement. Did you mean to break out of the outer loop'
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    paths:
      - generated
      - '.*\.pb\.go'
