version: 2
project_name: 'urlzap'

builds:
  - main: './cmd/urlzap/main.go'
    binary: 'urlzap'
    goos: ['linux', 'darwin', 'windows']
    goarch: ['amd64', 'arm64']

changelog:
  sort: 'asc'
  filters:
    exclude: ['^docs:', '^test:', 'Merge pull request', 'Merge branch']

archives:
  - format_overrides:
      - goos: 'windows'
        formats: ['zip']

nfpms:
  - formats: ['deb', 'rpm']
    maintainer: 'Bruno Luiz Silva <dev@brunoluiz.net>'
    dependencies: ['git']

# dockers:
#   - image_templates:
#     - 'brunoluiz/urlzap:{{ .Tag }}'
#     - 'brunoluiz/urlzap:v{{ .Major }}.{{ .Minor }}'
#     - 'brunoluiz/urlzap:latest'
#     dockerfile: 'Dockerfile.prod'
#     binaries:
#     - 'urlzap'

homebrew_casks:
  - name: urlzap
    repository:
      owner: brunoluiz
      name: homebrew-tap
