# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Urlzap < Formula
  desc ""
  homepage ""
  version "1.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/brunoluiz/urlzap/releases/download/v1.0.4/urlzap_1.0.4_darwin_amd64.tar.gz"
      sha256 "ade1badeee2168c07f5a3a2f92065249d07168ed50314024effc7f39990e5d16"

      define_method(:install) do
        bin.install "urlzap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/brunoluiz/urlzap/releases/download/v1.0.4/urlzap_1.0.4_darwin_arm64.tar.gz"
      sha256 "3d4da4502ec32c6306c743dee3ac336b316b1d90c37fa78858321ad74730f582"

      define_method(:install) do
        bin.install "urlzap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/brunoluiz/urlzap/releases/download/v1.0.4/urlzap_1.0.4_linux_amd64.tar.gz"
      sha256 "8ae7b7511aa1f9793c01fb3b8d59e2df9c482465b561af2850be9c8cd6032b35"
      define_method(:install) do
        bin.install "urlzap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brunoluiz/urlzap/releases/download/v1.0.4/urlzap_1.0.4_linux_arm64.tar.gz"
      sha256 "cb39a504361783ddfc23827478ee999038ec9c418bd62ebefb0eb881dc15905f"
      define_method(:install) do
        bin.install "urlzap"
      end
    end
  end
end
